Marie Candito - Master Linguistique Informatique - Université Paris Cité

**COPY THIS COLAB NOTEBOOK** if you want to modify it.

# Exercises on vectors and matrices

Answer the following questions using paper and pencil:


1.   Compute the dot product of $v1 = (1, -2, 2)$ and $v2=(-3, 6,2)$

2.   Compute the norm of $v1$ and $v2$

3.   Compute cos(v1,v2) in two ways
 - dot product divided by norm of v1 and norm of v2
 - first normalize v1 and v2 : divide each by their norm, and then compute the dot product between v1' and v2'

4.   Transpose the matrix $A = \begin{pmatrix}
 1 & -2 & 2\\
 -3 & 4 & 0\\
 4 & 2 & 4\\
 -2 & -2 & 1
 \end{pmatrix}$

5.   Let $B = \begin{pmatrix}
 -3 & 6 & 2\\
  0 & 3 & -4\\
 \end{pmatrix}$.
     - Can we compute the matrix product AB ?
     - (Remember matrix product $M_1M_2$ computes the dot product of every row in $M_1$ with every column in $M_2$)

6.   Find out which of these two matrix products is feasible, and compute it
   - $A(B^T)$
   - or $(A^T)B$
   - (drawing the matrices can help you)

7.   Describe in plain words (French or English) which dot products were computed in the previous question.



# Tensors in python: the ndarray type in numpy

The numpy.ndarray type can be used to represent multidimensional arrays
("n-dimensional" hence the name ndarray), corresponding to the mathematical concept of  **tensor**.

A one-dimensional array corresponds to a **vector** (= tensor with 1 axis (or dimension)).

A 2-dimensional array corresponds to a **matrix** (= tensor with 2 axis).

More generally, a n-dimensional array corresponds to a **tensor** with n **axis**.

An ndarray can be built with numpy methods such as zeros, ones, random.rand, arange ...


## Initialize and modify tensors

#### Initialization with zeros

In [45]:
import numpy as np

m1 = np.zeros( (3,4) ) # a matrix with 3 rows and 4 columns
                       # bidimensional ndarray
print(m1)

print(type(m1))

print(m1.shape)  # the "shape" is a tuple providing the size of each axis

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(3, 4)


In [46]:
m = np.array( [ [1,2], [3,4]])
print(m)

print(m[0,1])
print(type(m))

[[1 2]
 [3 4]]
2
<class 'numpy.ndarray'>


#### `np.array` : Initialization via lists of lists of lists ...

In [47]:
m3 = np.array([[1,2],[3,4],[5,6]])

print(m3)

print(m3.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [48]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  # tensor with 3 axis, 2x2x2
                                           # (cube, each face is a 2x2 matrix)
print(a)
print(a.shape)

# get one element : ranks along each axis starts at 0
print(a[1,0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
6


### Reshaping

In [49]:
# range + reshape
a = np.array (range(16))
print(a)
print(a.shape)

b = a.reshape(4,4)
print(b)
print(b.shape)

print(a.reshape(2,2,4))

# NB: reshape does not copy!!
b[1,0] = 0
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[ 0  1  2  3  0  5  6  7  8  9 10 11 12 13 14 15]


### Random initialization

In [50]:
m2 = np.random.rand(2,2)  # a 2x2 matrix, containing random floats between 0 and 1
print(m2)

[[0.23654888 0.58814774]
 [0.69115098 0.62306685]]


### linspace initialization

In [51]:
# linspace initialization
a = np.linspace(2.5, 10, 6)  # lower bound, upper bound, nb of elements
                           # = 6 elements, uniformely distributed
                           #   in the range [2.5, 10]
print(a)
type(a)
print(a.shape)

[ 2.5  4.   5.5  7.   8.5 10. ]
(6,)


### Get or set subparts of a tensor

In [52]:
a = np.array (range(12))
a = a.reshape(4,3)
print(a)

# get one value
print(a[1,0])   # first index (axis=0) = id of the row (starting at 0)
                # 2nd index   (axis=1) = id of the column (starting at 0)

# slices do work as in lists
# => use ":" to select a whole row / column etc...

# selecting the 3rd row
print(a[2, :])

# CAUTION: choosing a single value on one of the axis removes this axis altogether
# => the shape has 1 axis less
# => here we get a vector of shape (3,) and not a matrix of shape (1,3)
print(a[2, :].shape)

# selecting 2nd and 3rd columns (hence with ids 1 and 2)
print(a[:, 1:3])
# here the shape still has the same nb of axis
print(a[:, 1:3].shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3
[6 7 8]
(3,)
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
(4, 2)


In [53]:
a = np.array (range(12)).reshape(4,3)

# modification of 1st column
a[:, 0] = np.zeros( shape=(4,))
print(a)

# modification of 2nd row
a[1, :] = np.ones( shape=(3,))
print(a)

# directly assigning the 3rd row
a[2, :] = [-1, -7, -1]
print(a)


[[ 0  1  2]
 [ 0  4  5]
 [ 0  7  8]
 [ 0 10 11]]
[[ 0  1  2]
 [ 1  1  1]
 [ 0  7  8]
 [ 0 10 11]]
[[ 0  1  2]
 [ 1  1  1]
 [-1 -7 -1]
 [ 0 10 11]]


In [54]:
# the same holds for tensors with more than 2 axis
t3 = np.array(range(24)).reshape(3,4,2)  ## 3 matrices de size 4 x 2
print(t3)

print( t3[0,:,:] )

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [55]:
a = np.array (range(24))
a = a.reshape(2,3,4)  # a tensor with 3 axis
print(a)

b = a[0,:,:]
print(b.shape)  # 2 axis left
print(b)

c = a[1,:,2]
print(c.shape)  # 1 axis left
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3,)
[14 18 22]


### CAUTION: assigning does not copy

In [56]:
# CAUTION: assigning does not copy
a = np.ones(shape=(3,4))
b = a
a[1,2] =17
print("a", a)
print("b", b)

c=np.copy(a)
a[1,3]=2
print("a", a)
print("c", c)

a [[ 1.  1.  1.  1.]
 [ 1.  1. 17.  1.]
 [ 1.  1.  1.  1.]]
b [[ 1.  1.  1.  1.]
 [ 1.  1. 17.  1.]
 [ 1.  1.  1.  1.]]
a [[ 1.  1.  1.  1.]
 [ 1.  1. 17.  2.]
 [ 1.  1.  1.  1.]]
c [[ 1.  1.  1.  1.]
 [ 1.  1. 17.  1.]
 [ 1.  1.  1.  1.]]


### Transposition

In [57]:
# sometimes needed to change rows into columns
a = np.array (range(8)).reshape(2,4)
b = a.transpose()
print(a)
print(b)

# can be done also with .T
c = a.T
print(c)


[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


## Vector vs matrix with one row or one column

In [58]:
v1 = np.array ([5,6,7], float)  # a real-valued vector of size 3
                                # equivalent to a list, but all elements must have the same type
print(v1)
print (type(v1))
print (v1.shape) # a tuple of length one for the shape of one-dimensional ndarrays

[5. 6. 7.]
<class 'numpy.ndarray'>
(3,)


In [59]:
v2 = np.zeros( (4,) )
print(v2)
print(v2.shape)

[0. 0. 0. 0.]
(4,)


In [60]:
# caution: vector of shape (n,) versus matrix with shape (n,1) or (1,n)
vect = np.ones((3,))
mat1 = np.ones((3,1))
mat2 = np.ones((1,3))

print(vect)
print(mat1)
print(mat2)

[1. 1. 1.]
[[1.]
 [1.]
 [1.]]
[[1. 1. 1.]]


## Sorting with np.sort et np.argsort

In [61]:
a = np.array( [ 3 , 24, 17, 8, 2 ,16]).reshape(2,3)

# sorting, with varying columns (axis=1)
#          => corresponds to sorting each row
b = np.sort(a, axis=1)
# sorting, with varying rows (axis=0)
#          => corresponds to sorting each column
c = np.sort(a, axis=0)
print(a)
print(b)
print(c)

[[ 3 24 17]
 [ 8  2 16]]
[[ 3 17 24]
 [ 2  8 16]]
[[ 3  2 16]
 [ 8 24 17]]


In [62]:
# we may need to sort the ids according to the values
# => argsort provides the ids sorted according to the values
b = np.argsort(a, axis=1)
print(a)
print("b", b)
# the sorted ids give access to the sorted values if needed
print("sorted first row:", [ a[0,i] for i in b[0]])

c = np.argsort(a, axis=0)
# QUESTION: what will be the value of c?
# C = [ 0, 1, 1]
#    [ 1, 0, 0]
print(c)

[[ 3 24 17]
 [ 8  2 16]]
b [[0 2 1]
 [1 0 2]]
sorted first row: [3, 17, 24]
[[0 1 1]
 [1 0 0]]


In [63]:
# to get descending order, we can just sort the opposite tensor (-a)
d = np.argsort(-a, axis=1)
print(d)

[[1 2 0]
 [2 0 1]]


## Applying a function to each element of a tensor

### Operations between a tensor and a scalar

In [64]:
# multiplication by a scalar, addition of a scalar etc...
a = np.array(range(6)).reshape(2,3)

print(a)

print(a + 10)
print(a * 10)
print(a / 10.0)
print(a**2)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[ 0 10 20]
 [30 40 50]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]]
[[ 0  1  4]
 [ 9 16 25]]


### Applying a mathematical function to each element

See list of numpy mathematical functions
https://numpy.org/doc/stable/reference/routines.math.html

In [65]:
a = np.array(range(8)).reshape(2,4) + 1
print(a)
print(np.log2(a)) # log base 2 applied to each cell

[[1 2 3 4]
 [5 6 7 8]]
[[0.         1.         1.5849625  2.        ]
 [2.32192809 2.5849625  2.80735492 3.        ]]


In [66]:
m = np.random.rand(2,2)
print(m)


[[0.83981989 0.57197041]
 [0.18396065 0.62771906]]


### TODO: comment what is done with:


In [67]:
print(np.round(m, 2))
# [0.94 0.27]
# [0.40 0.87]

[[0.84 0.57]
 [0.18 0.63]]


### Applying a user-defined method to each element

In [68]:
# np.vectorize defines a "vectorized" version of any function my_f
# namely a version that will apply my_f to each cell

def my_f(x):
    if (x<2):
        return 2 * x
    else:
        return 3 * x+1

my_f_vec = np.vectorize(my_f)

a = np.array(range(6)).reshape(2,3)
print(a)
print(my_f_vec(a))

# QUESTION: what will contain a * f_vec(a) ?
# Problem in the question



[[0 1 2]
 [3 4 5]]
[[ 0  2  7]
 [10 13 16]]


### Applying a function along one or several axes : e.g. get the sum for each row of a matrix

`np.sum`is quite useful.

The `axis` argument serves to define which elements to sum.


In [69]:
a = np.array(range(6)).reshape(2,3)
print(a)

print(np.sum(a))          # by default: sum of all cells (axis=None)

# the axis argument serves to define which elements to sum
# more precisely which axis or tuple of axes varies to sum elements
# it is easier to think of which axis *does not vary*
print(np.sum(a, axis=0))  # sum with varying rows => keep separated sums for each column
print(np.sum(a, axis=1))  # sum with varying columns => sum of each row
print(np.sum(a, axis=-1)) # axis=-1 means the last axis, here =1



[[0 1 2]
 [3 4 5]]
15
[3 5 7]
[ 3 12]
[ 3 12]


In [70]:
a = np.array(range(12)).reshape(2,3,2)

print(a)
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

# axis can also be a tuple of axes
# e.g. sum with varying axes 1 and 2
#      only axis 0 does not vary : keep separate sums for each of the 2 2x3 matrices
print(np.sum(a, axis=(1,2)))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[ 6  9]
 [24 27]]
[[ 6  8]
 [10 12]
 [14 16]]
[15 51]


### TODO: use np.prod to obtain for each column, the product of the elements in the column


In [71]:
a = np.array(range(6)).reshape(2,3)
print(a)
print(np.prod(a, axis=0))


[[0 1 2]
 [3 4 5]]
[ 0  4 10]


## Element-wise operations between two tensors of same shape

In [72]:
# for two tensors of same shape, using arithmetic operators will apply
#the operators to each pair of elements at same coordinates in the tensors

a = np.array(range(12)).reshape((3,4))
print(a)

b = np.array(range(12)).reshape((3,4)) + 2
print(b)

print(a * b) # => NB: corresponds to the Hadamard product

print (a / b)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[  0   3   8  15]
 [ 24  35  48  63]
 [ 80  99 120 143]]
[[0.         0.33333333 0.5        0.6       ]
 [0.66666667 0.71428571 0.75       0.77777778]
 [0.8        0.81818182 0.83333333 0.84615385]]


In [73]:
a = np.array(range(12)).reshape(3,4)
print(a)
print(a*a)
print(np.sum(a*a, axis=1))
print(np.sqrt(a**2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[ 14 126 366]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


## dot product (for vectors) and matrix product

### dot product of two vectors : np.dot

NB: np.dot has different behavior depending on the input shapes
see https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [74]:
v1 = np.array([1, -2, 2])
v2 = np.array([-3, 6, 2])

np.dot(v1, v2)

-11

### Matrix product : np.matmul and the @ operator

**Essential**:

C = AB

**C\[i,j\] equals the dot product between i-th row of A and j-th column of B**

Hence AB is only defined when number of columns of A = number of lines of B

In numpy, use np.matmul or the infix @ operator

Rem: np.dot also works on matrices but not recommended

In [75]:
a = np.array(range(6)).reshape(2,3)
b = np.array(range(12)).reshape(3,4)

print(a)
print(b)

print(a @ b)

print(np.matmul(a,b))

# rem:
# A @ B @ C
# is equivalent to
# np.matmul(np.matmul(A,B), C)


[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[20 23 26 29]
 [56 68 80 92]]
[[20 23 26 29]
 [56 68 80 92]]


### TODO: comment the operations below

In [76]:

a = np.array(range(6)).reshape(2,3)
b = np.array(range(12)).reshape(4,3)
c = np.matmul(a, b.transpose()) # We transpose b to have the same number of columns
print(a)
print(b)
print(c) # 2x4 matrix

[[0 1 2]
 [3 4 5]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  5  14  23  32]
 [ 14  50  86 122]]


## Product of vector and matrix

In [77]:
# The np.matmul method does implicit reshaping
# when one of the arguments is uni-dimensional

# if x is a vector of size n (array of shape (n,))
# then when x is first argument of np.matmul
# => reshape as a line vector (1,n)
M = np.arange(6).reshape(3,2)
v = np.arange(3) + 10
print(M)
print(v)
d = np.matmul(v,M)
print("np.matmul(v,M):", d)
print("shape:", d.shape)


[[0 1]
 [2 3]
 [4 5]]
[10 11 12]
np.matmul(v,M): [ 70 103]
shape: (2,)


### TODO: check that this line produces an error, explain why

In [78]:
#print(np.matmul(M,v)) 
# M is a matrix (3,2) and v is a line vector (1, 3) => impossible

In [79]:
print(M.T)
print(v)
print (np.matmul(M.T,v))
# same as:
print (M.T @ v) # The vector can be considered as a column vector (3,1)

[[0 2 4]
 [1 3 5]]
[10 11 12]
[ 70 103]
[ 70 103]


In [80]:
# when x is 2nd argument of @
M = np.arange(6).reshape(2,3)
v = np.arange(3) + 10
print(M)
print(v)

print("M @ v result using explicit reshaping of v as column vector :")
r = M @ v.reshape(3,1)
print(r)
print(r.shape)

print("M @ v result with IMPLICIT reshaping:")
print(M @ v)
print("is equivalent to v @ M.T")
print(v @ M.T)



[[0 1 2]
 [3 4 5]]
[10 11 12]
M @ v result using explicit reshaping of v as column vector :
[[ 35]
 [134]]
(2, 1)
M @ v result with IMPLICIT reshaping:
[ 35 134]
is equivalent to v @ M.T
[ 35 134]


## Other operations between a matrix and a vector : implicit repetition of the vector

In [81]:
# matrix and vector (=> the vector (n,) is interpreted as a ROW (1,n))
m = np.array(range(12)).reshape((3,4))
print(m)
print(-m)

v = np.array(range(4)) + 2
print( "vector v:", v, ", with shape", v.shape )
print( "m + v: \n", m + v )

print("Operation between matrix m with shape (r,c) and vector v with shape (c,) :")
print("Everything happens as if the vector were repeated on n rows")



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
vector v: [2 3 4 5] , with shape (4,)
m + v: 
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]
Operation between matrix m with shape (r,c) and vector v with shape (c,) :
Everything happens as if the vector were repeated on n rows


Other operations like - / * work in the same way

### TODO: use paper and pencil to redo the following operation


In [82]:
print( "- m * v: \n",  -m * v )

print( "(-2 * m) - v: \n", (-2 * m) / v )


- m * v: 
 [[  0  -3  -8 -15]
 [ -8 -15 -24 -35]
 [-16 -27 -40 -55]]
(-2 * m) - v: 
 [[ 0.         -0.66666667 -1.         -1.2       ]
 [-4.         -3.33333333 -3.         -2.8       ]
 [-8.         -6.         -5.         -4.4       ]]


In [83]:
# to do an operation between a matrix and a vector used as a column
# you need to convert the vector as a real matrix with a single column
M = np.array(range(12)).reshape((3,4))
print(M)
v = np.array(range(3)).reshape((3,))

print("v: ", v)
print("v.shape", v.shape)
print("shape when using asmatrix method:", np.asmatrix(v).shape)

# this gives an error, why? they removed this error ? Bc they consider v as a column vector
#print(M * v)

# use reshape to see v as a column vector
c = v.reshape(3,1)
print("v as a column vector (a matrix with 3 rows and one column):\n", c)
print("Operation between a matrix (3,4) and a column matrix c (3,1) :")
print("Everything happens as if the column in v were repeated as 4 identical columns")
print("M * c =")
print(M * c)

print("M + c =")
print(M + c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
v:  [0 1 2]
v.shape (3,)
shape when using asmatrix method: (1, 3)
v as a column vector (a matrix with 3 rows and one column):
 [[0]
 [1]
 [2]]
Operation between a matrix (3,4) and a column matrix c (3,1) :
Everything happens as if the column in v were repeated as 4 identical columns
M * c =
[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]
M + c =
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


# Numpy exercise : batch computation of distances and similarities

We take again matrices $A = \begin{pmatrix}
 1 & -2 & 2\\
 -3 & 4 & 0\\
 4 & 2 & 4\\
 -2 & -2 & 1
 \end{pmatrix}$ and $B = \begin{pmatrix}
 -3 & 6 & 2\\
  0 & 3 & -4\\
 \end{pmatrix}$.



## TODO1:
Use numpy methods to compute the cosine similarity for each row vector in A with each row vector in B, **without using any loop over rows or columns**, which will be much more efficient.

**Indications**: remember that cos(u, v) = u'.v', with u' being the normalized version of u (namely u divided by its norm). So
- define A and B as above
- start by computing the norms of each row vector in A and B (square and sum!)
- divide each row vector in A and B by its norm
- and then use matrix multiplication to compute the required dot products



In [84]:
v1 = np.array([1, -2, 2])
v2 = np.array([-3, 6, 2])
cosine_similarity = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
cosine_similarity

-0.5238095238095238

In [85]:
A = np.array([[1, -2, 2], [-3, 4, 0], [4, 2, 4], [-2, -2, 1]])
B = np.array([[-3, 6, 2], [0, 3, -4]])

A_square_sum = np.sum(A ** 2, axis=1)
# Racine carrée de la somme des carrés des éléments de chaque ligne
A_square_sum_sqrt = np.sqrt(A_square_sum)
A_square_sum_sqrt = A_square_sum_sqrt.reshape((4, 1))

B_square_sum = np.sum(B ** 2, axis=1)
B_square_sum_sqrt = np.sqrt(B_square_sum)
B_square_sum_sqrt = B_square_sum_sqrt.reshape((2, 1))

A_divided = A / A_square_sum_sqrt
print("A_divided:", A_divided)
B_divided = B / B_square_sum_sqrt
print("B_divided:", B_divided)

C = np.matmul(A_divided, B_divided.T)
C

A_divided: [[ 0.33333333 -0.66666667  0.66666667]
 [-0.6         0.8         0.        ]
 [ 0.66666667  0.33333333  0.66666667]
 [-0.66666667 -0.66666667  0.33333333]]
B_divided: [[-0.42857143  0.85714286  0.28571429]
 [ 0.          0.6        -0.8       ]]


array([[-0.52380952, -0.93333333],
       [ 0.94285714,  0.48      ],
       [ 0.19047619, -0.33333333],
       [-0.19047619, -0.66666667]])

## Utility for K-NN
This efficient computation will be useful to implement the K-NN algorithm *in a very efficient way*:
- if A is for 4 vectors for which we know the class.
- and B is for 2 vectors to classify using K-NN
Then for each vector in B, we will need to compute the distance (or cosine similarity) with each vector in A.



## TODO2:
Do the same for Euclidian distance instead of cosine.

**Indications**: use the following reformulation of distances:

$ dist(a,b) = \lVert a - b \rVert = \sqrt{\sum_{i=1}^d (a_i - b_i)^2}$
$= \sqrt{\sum_{i=1}^d (a_i^2 + b_i^2 - 2 a_i b_i)}$
$= \sqrt{\lVert a \rVert^2 + \lVert b \rVert^2 - 2 a \cdot b}$

In [90]:
A_Norm_square = np.sum(A ** 2, axis=1)
A_Norm = A_Norm_square.reshape((4, 1))
B_Norm_square = np.sum(B ** 2, axis=1)
B_Norm = B_Norm_square.reshape((2, 1))
print(A_Norm)
print(B_Norm)
AdotB = 2 * np.matmul(A, B.T)
print(AdotB)

D = A_Norm + B_Norm.T - AdotB
D = np.sqrt(D)
D


[[ 9]
 [25]
 [36]
 [ 9]]
[[49]
 [25]]
[[-22 -28]
 [ 66  24]
 [ 16 -20]
 [ -8 -20]]


array([[8.94427191, 7.87400787],
       [2.82842712, 5.09901951],
       [8.30662386, 9.        ],
       [8.1240384 , 7.34846923]])

In [87]:
v1 = np.array([1, -2, 2])
v2 = np.array([-3, 6, 2])
euclidean_distance = np.linalg.norm(v1 - v2)
print(euclidean_distance)

8.94427190999916
